### ISSUE TITLE
Calculate Missing Fields to Punish Miner Utility Score

### ISSUE THREAD

**Issue by grantdfoster** [masa-finance/masa-bittensor#123]
Follow up task for https://github.com/masa-finance/masa-bittensor/issues/11

✅ **Valid Fields** (vF, w1):  Miners should be punished for missing fields, not necessarily rewarded for having correct ones.  Score can be decremented by a certain value for every missing field.  Possible expansion into utilizing `client version`, and punishing those nodes running stale versions of the protocol (future case).  Example weight: 0.3

**Comment by grantdfoster** [comment]
## Update
Putting this on pause as we wait for the outcome of https://github.com/masa-finance/issues/issues/197, which likely implements a better mechanism for scoring valid data.

**Comment by juanmanso** [comment]
I think this is a smaller task of [masa-finance/issues#197](https://github.com/masa-finance/issues/issues/197), so I'd suggest to close it.

To show this even more, I'd move this to `Ready` since it's paused and add a `blocked` label to show the dependency. On grooming/planning we can decide if we can close it or not (adding also the `triage` label)

**Comment by giovaroma** [comment]
Locking down version to participate. Ticket to be updated by @grantdfoster @hide-on-bush-x

**Comment by mudler** [comment]
This is covered by https://github.com/masa-finance/masa-bittensor/pull/166
