### ISSUE TITLE
Spike: Miners outsmarting our scoring process

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#204]

**Comment by grantdfoster** [comment]
This spike was created from the pre-mortem for going to mainnet.  We have already addressed this concern with our v1 scoring logic, which incorporates the concept of a "source of truth", instead of just checking JSON properties.  [This PR](https://github.com/masa-finance/masa-bittensor/pull/198) implements an even better scoring logic, scoring miner responses specifically on how similar they are to said source of truth.  From my point of view, nothing more needs to be done w/ this spike, and we will constantly be monitoring the network for malicious behavior.

**Comment by teslashibe** [comment]
@grantdfoster agreed on this - @Luka-Loncar this can be closed

**Comment by teslashibe** [comment]
@grantdfoster agreed on this - @Luka-Loncar this can be closed
