### ISSUE TITLE
Spike: malicious validators only calling a hard-coded list of malicious miners

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#206]

**Comment by grantdfoster** [comment]
We potentially could do more research here but it is our understanding that the way to prevent this is to have many validators that we control, all "benevolent".  If this is the case, malicious validators will then be scored poorly b/c they are not following the herd in terms of the weights they set.  We should investigate:

1. how to weight copy, or even if we _should_ do that, because we can also:
2. run many independent validators, improving the decentralization of the network

**Comment by Luka-Loncar** [comment]
I'm creating these 2 new spikes and closing this issue.
