### ISSUE TITLE
Feat: Deploy private subnet node for Masa

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#239]
This is now available and set up like so:

CNAME defined in cloudflare: entrypoint-finney.masa.ai that proxies requests to our NLB in our AWS account (masa-opentensor-main) -- this lets use use cloudflare features like DDOS protection and caching as a first line of defense for our public facing subtensor node

NLB has an ACM certificate associated for the domain entrypoint-finney.masa.ai, so it is able to terminate (decrypt) the incoming SSL connection from cloudflare when it arrives.

The NLB then sends the decrypted websocket connection to port 9944 of the instance(s) in the target group associated to the NLB. These instances will only accept requests from the NLB, they are not publicly exposed. (except also I can ssh into them from my home IP)

The instance(s) run the subtensor node code as a service and are configured as "lite" (rather than "archive") nodes.

TO DO: terraformize / document this deployment in the terraform repo (masa-oracle-infra).

**Comment by Luka-Loncar** [comment]
For @5u6r054

**Comment by 5u6r054** [comment]
We now have one "lite" subtensor node up and running in our masa-opentensor-main account at 35.153.141.194 

we still need to test it out more, but it's up and running as a service on the machine and syncing.

**Comment by 5u6r054** [comment]
This is now available and set up like so:

CNAME defined in cloudflare: entrypoint-finney.masa.ai that proxies requests to our NLB in our AWS account (masa-opentensor-main) -- this lets use use cloudflare features like DDOS protection and caching as a first line of defense for our public facing subtensor node

NLB has an ACM certificate associated for the domain entrypoint-finney.masa.ai, so it is able to terminate (decrypt) the incoming SSL connection from cloudflare when it arrives. 

The NLB then sends the decrypted websocket connection to port 9944 of the instance(s) in the target group associated to the NLB. These instances will *only* accept requests from the NLB, they are not publicly exposed. (except also I can ssh into them from my home IP)

The instance(s) run the subtensor node code as a service and are configured as "lite" (rather than "archive") nodes.
