### ISSUE TITLE
Add CI test coverage

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-bittensor#253]
## Problem

We want to assess the code quality, but we don't know the test coverage of the code

## Action item

- [x] Collect coverage of current unit tests automatically
- [ ] Use a service like codecov to upload the coverage 
- [ ] Use a service like codecov and hook it to the CI/CD to allow us to evaluate the code coverage

**Comment by giovaroma** [comment]
Bittensor removed functionality from BT SDK and now need to figure out how to fix this. Working with Bittensor to come up with a solution.

**Comment by hide-on-bush-x** [comment]
Some notes about what happened:
- Bittensor SDK update removed all the mocks we were using to test, it seems like they are not bringing them back ( conversation in the church of rao )
- Since that broke our old unittests we needed to figure out how achieve some E2E 
     - Decided to test on BT Testnet subnet 165 
            - This requires testnet registered wallets to work ( cc @John Durkin, we are going to set up a common set of wallets for this kind of dev purposes on 1p )
- Got some minimal tests running for the miner and the validator and got coverage report from it
      - There is a script inside the tests folder that takes care of running those tests and get the report, its important to use it because if we run the tests in parallel it fails ( it has to be secuential )

**Comment by Luka-Loncar** [comment]
Follow up task https://github.com/masa-finance/masa-bittensor/issues/294
