### ISSUE TITLE
Create status page for Devnet

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#51]

**Comment by juanmanso** [comment]
Would require more info to further scope the task:
- Who is the intended/target user to use this page?
- Is there any reason to develop this instead of using an already well developed solution as Taostats.io?
  - Other than it's targeted for devnet?
- How is this page meant to be used?
- A design is required for it
- Should this be a section of the SBT app? Or should this be like the `analytics` part of the app?

I want to emphasis that these things should be scoped by Stakeholders and Roadmap Owners _before_ the planning so we can have some buffer time to review these and use as little time as possible on the planning reviewing them.

**Comment by grantdfoster** [comment]
Closing this issue, we no longer run a devnet, in favor of using Bittensor's testnet.
